name: MLOps CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test and Validate Model
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: pip

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Train Model
        run: |
          python retrain.py

      - name: Validate Model
        run: |
          python validate_model.py

      - name: Run Tests
        run: |
          pytest -v

      - name: Bandit Security Scan
        run: |
          mkdir -p security/bandit

          python -m bandit \
            -r . \
            -x ./venv,./tests \
            -f json \
            -o security/bandit/bandit-report.json

      - name: Upload Bandit Report
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: bandit-report
          path: security/bandit/bandit-report.json
          if-no-files-found: warn

      - name: pip-audit
        run: |
          mkdir -p security/pip-audit

          pip-audit \
            -r requirements.txt \
            -f json \
            -o security/pip-audit/pip-audit-report.json

      - name: Upload pip-audit Report
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: pip-audit-report
          path: security/pip-audit/pip-audit-report.json
          if-no-files-found: warn

      - name: Verify Model Artifact
        run: |
          test -f models/model.pkl
          ls -lh models/model.pkl

      - name: Upload Model Artifact
        uses: actions/upload-artifact@v5
        with:
          name: iris-model
          path: models/model.pkl
